SELECT*FROM CovidDeaths
WHERE CONTINENT IS NOT NULL
ORDER BY 3,4;

--- SELECT*FROM CovidVaccinations
--- ORDER BY 3,4;

--- SELECCION DE DATA A USAR
SELECT LOCATION,DATE,TOTAL_CASES, NEW_CASES, TOTAL_DEATHS,POPULATION
FROM CovidDeaths
ORDER BY 1,2;

--- DETERMINAR EL TOTAL DE CASOS VS EL TOTAL DE MUERTES PERU
SELECT LOCATION,DATE,TOTAL_CASES, TOTAL_DEATHS,ROUND(TOTAL_DEATHS/TOTAL_CASES,2)*100 AS PORCENTAJE_MUERTES
FROM CovidDeaths
WHERE LOCATION='PERU'
ORDER BY 1,2;

--- TOTAL CASOS VS POBLACION PERU
-- PORCENTAJE POBLACION DE PERU QUE ADQUIRIO COVID
SELECT LOCATION,DATE,TOTAL_CASES,POPULATION, ROUND(TOTAL_CASES/POPULATION,2)*100 AS PORCENTAJE_CASOS
FROM CovidDeaths
WHERE LOCATION='PERU'
ORDER BY 1,2;

--- PAISES CON LOS % DE INFECCION MAS ALTOS
SELECT LOCATION,POPULATION, MAX(TOTAL_CASES) AS CONTEO_CASOS, MAX(ROUND(TOTAL_CASES/POPULATION,2)*100) AS PORCENTAJE_CASOS
FROM CovidDeaths
--WHERE LOCATION='PERU'
GROUP BY POPULATION, LOCATION
ORDER BY PORCENTAJE_CASOS DESC;

--- CONTINENTES CON LOS % DE DECESOS MAS ALTOS
SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS INT)) AS CONTEO_MUERTES
FROM CovidDeaths
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY CONTEO_MUERTES DESC;

--- PAISES CON LOS % DE DECESOS MAS ALTOS
SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS CONTEO_MUERTES
FROM CovidDeaths
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY CONTEO_MUERTES DESC;


--- DATOS GLOBALES
SELECT DATE,SUM(NEW_CASES) AS TOTAL_NUEVOSCASOS, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_NUEVASMUERTES, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS PORCENTAJE_MUERTES ---TOTAL_DEATHS,ROUND(TOTAL_DEATHS/TOTAL_CASES,2)*100 AS PORCENTAJE_MUERTES
FROM CovidDeaths
WHERE CONTINENT IS NOT NULL
GROUP BY DATE
ORDER BY 1,2;


--- POBLACION MUNDIAL VS VACUNAS APLICADAS POR DIA
--TABLA TEMPORAL
WITH POPVSVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS,VACUNAS_APLICADAS)
 AS 
 (SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS,
SUM(CAST(VAC.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS VACUNAS_APLICADAS
--ROUND(POBLACION_VACUNADA/POPULATION)*100
FROM CovidVaccinations VAC
JOIN CovidDeaths DEA
ON VAC.location=DEA.location
AND VAC.date=DEA.date
WHERE DEA.CONTINENT IS NOT NULL
--ORDER BY 2,3
)
SELECT *, (VACUNAS_APLICADAS/POPULATION)*100 AS PORC_VACUNAS_APLICADAS
FROM POPVSVAC;

-- CREAR VISTA
CREATE VIEW VACUNAS_APLICADAS AS
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS,
SUM(CAST(VAC.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS VACUNAS_APLICADAS
--ROUND(POBLACION_VACUNADA/POPULATION)*100
FROM CovidVaccinations VAC
JOIN CovidDeaths DEA
ON VAC.location=DEA.location
AND VAC.date=DEA.date
WHERE DEA.CONTINENT IS NOT NULL
--ORDER BY 2,3

SELECT*FROM VACUNAS_APLICADAS